### ISSUE TITLE
Remap delete and cut keys to blackhole register

### ISSUE THREAD

**Issue by Shatur** [gbprod/cutlass.nvim#1]
https://github.com/svermeulen/vim-cutlass by default remaps `c, cc, C, s, S, d, dd, D, x, X` to blackhole register. I would suggest to add it.

**Comment by Shatur** [comment]
Oh, sorry, I just forgot to call `require('cutlass').setup()`, my bad.

**Comment by gbprod** [comment]
No problem ;)
