### ISSUE TITLE
delete operator does not work with Leap.nvim motions

### ISSUE THREAD

**Issue by msprev** [gbprod/cutlass.nvim#17]
The new delete operator cannot be fed with [Leap.nvim](https://github.com/ggandor/leap.nvim) motions.

Steps to reproduce:

1. Enter delete operator pending mode (press `d` or `c`)
2. Attempt to supply a Leap motion (e.g. `s`)
3. Motion is not detected and Leap is not activated

NB. The remapped `cut_key` (e.g. `m`) works correctly with Leap motions.

Context:

- [Leap.nvim](https://github.com/ggandor/leap.nvim) installed
- `vim.keymap.set({ "n", "x", "o" }, "s", "<Plug>(leap-forward-to)", { remap = false })`

**Comment by gbprod** [comment]
Hey!
Thanks for reporting this issue.

Can you try removing the `remap` option ?

```lua
vim.keymap.set({ "n", "x", "o" }, "s", "<Plug>(leap-forward-to)", { })
```

**Comment by msprev** [comment]
Thanks, this has prompted me to trying changing the remapped key and this eliminated the problem. I realised that the issue was not cutlass but that `ds` and `cs` were already remapped by nvim-surround and were clobbering the Leap.nvim mapping. Closing the issue now as it was due to user error!
