### ISSUE TITLE
Lightspeed

### ISSUE THREAD

**Issue by sayit358** [gbprod/cutlass.nvim#3]
Is there some way for this plugin to not use certain keys such as s and S? Lightspeed uses those keys and it doesn't work anymore.

**Comment by gbprod** [comment]
Hi !
As you can see [here](https://github.com/gbprod/cutlass.nvim/blob/main/lua/cutlass.lua#L37), this plugin is not supposed to remap keys that have already been mapped, and lightspeed seems to [work that way too](https://github.com/ggandor/lightspeed.nvim/blob/main/lua/lightspeed.lua#L2441).
I've you tried to call `require("cutlass.nvim").setup()` after `require("lightspeed").setup()` ?
If it doesn't works, I'll look further. Can you provide a minimal config to reproduce your problem ?

**Comment by sayit358** [comment]
That actually worked. I forgot you could do that. Thanks! :heart:

**Comment by gbprod** [comment]
FYI, I've implemented a new option to manage lightspeed, have a look to the documentation 😉
