### ISSUE TITLE
Comments.nvim doesn't work

### ISSUE THREAD

**Issue by EpsilonKu** [gbprod/cutlass.nvim#4]
Comments.nvim is not working with `gc` key on `visual` mode.

**Comment by gbprod** [comment]
Hello !
I use cutlass and comments.nvim and I don't have your problem.
I don't think that your problem comes from cutlass plugin as it doesn't create mappings on "g" or "gc" on visual mode.
Can you provide a minimal config to.reproduce your problem ? Does it works if you disable cutlass ?

**Comment by EpsilonKu** [comment]
I tried minimal config with only `cutlass.nvim` and `comment.nvim` and it works. But I can't made config to reproduce problem. If I remove `cutlass.nvim` from my config, `comment.nvim` work perfect. IDk, do you have any idea which plugin is problem? There is my [config](https://github.com/EpsilonKu/nvim). I will try to make minimal config for porblem.

**Comment by EpsilonKu** [comment]
```  
- WARNING: conflicting keymap exists for mode **"v"**, lhs: **"g"**
- INFO: rhs: `<C-O>"_cg`
```
This is what `:checkhealth` of `which-key` tells. Could not find which plugin is making. I guess it's default of plugin.

**Comment by gbprod** [comment]
This plugin only map `g` key in select mode, not in visual mode. It would be easier for me to help you if you can provide a minimal config to reproduce the problem.
I've you try to setup cutlass.nvim after/before comments.nvim ?
As cutlass does not override existing mappings, it's recommended to setup it lastly.

**Comment by EpsilonKu** [comment]
Ok, I find why. So I set `timeoutlen` to `0`. That's why.

**Comment by gbprod** [comment]
👍
