### ISSUE TITLE
Cannot exclude dd

### ISSUE THREAD

**Issue by lolobu** [gbprod/cutlass.nvim#9]
Hello,
I'm trying to exclude the sequence "dd" so that in normal mode, if I do a "dd" on a line, the deleted lines does go into the normal yank register. Basically, I would like that "nd" goes to the black hole register, but not "ndd" and "xd".
Excluding "xd" works perfectly, but excluding "ndd" doesn't.

exclude = {"ndd","xd"}

**Comment by gbprod** [comment]
Hmmm that's strange, I'll quickly try to fix it. 

For the moment, I don't like my implementation of exclude option, I think I will improve it soon.

Thx

**Comment by gbprod** [comment]
Ok, I've looked at your problem and it seems that the better solution in my opinion for the moment is to remap `dd` after `setup`.

Basicly : 

```lua
require("cutlass").setup({exclude = { "ndd", "xd" }})
vim.api.nvim_set_keymap("n", "dd", "dd", { noremap = true })
